services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: unless-stopped

  # rtsptoweb:
  stream-server:
    restart: unless-stopped
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ./RtspConfig.json:/config/config.json
    ports:
      - "8080:8080"


  # teleicu-middleware
  teleicu-middleware:
    restart: unless-stopped
    image: ghcr.io/10bedicu/teleicu_gateway:latest
    command: ["sh", "-c", "/app/start-backend.sh"]
    depends_on:
      - redis
      - stream-server
      - db
    env_file:
      - ./.env
    ports:
      - "8090:8090"

  celery:
    restart: unless-stopped
    image: ghcr.io/10bedicu/teleicu_gateway:latest
    command: ["sh", "-c", "/app/start-celery.sh"]
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - teleicu-middleware

  # proxies requests to internal services
  reverse-proxy:
    restart: unless-stopped
    image: ghcr.io/10bedicu/teleicu_gateway_nginx:latest
    depends_on:
      - teleicu-middleware
    ports:
      - "8001:8001"

volumes:
  postgres-data:
